spring.application.name=config-server
server.port=8888

spring.cloud.config.server.git.uri=file:///C:/PROYECTOS/Proyecto SOA/AsistIA---Sistema-de-Asistencia-con-IA/Back/ecom-Spring/config-repo
spring.cloud.config.server.git.default-label=master

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
