spring.application.name=config-server
server.port = 8888
spring.cloud.config.server.git.force-pull=true
spring.cloud.config.server.git.delete-untracked-branches=true
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.health.repositories.test.name=config-repo
spring.cloud.config.server.health.repositories.test.label=main
spring.cloud.config.server.git.uri=https://github.com/Darkrius/config-repo.git
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
