
spring.application.name=Asistencia-service
server.port=8083
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.cloud.config.label=main
spring.config.import=optional:configserver:http://localhost:8888
rsa.public-key=classpath:certs/public.pem
spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000